### ISSUE TITLE
Switch to submodules in GH actions about MacKernelSDK (GH actions on kexts)

### ISSUE THREAD

**Issue by tiziodcaio** [acidanthera/bugtracker#1681]
I saw you twice use checkout to trickly clone MacKernelSDK (in every kext github actions), but how about doing it with submodules?

Before:

```yaml
name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: KEXT

jobs:
  build:
    name: Build
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: acidanthera/MacKernelSDK
          path: MacKernelSDK
# [...]
```

Once, type this command in the folder to add the submodule ([further docs](https://git-scm.com/docs/gitmodules)

```bash
git submodule add https://github.com/acidanthera/MacKernelSDK.git MacKernelSDK
```

Then modify the action
```yaml
name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: KEXT

jobs:
  build:
    name: Build
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Submodules updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git submodule update --remote --recursive
          git pull && git commit -am "Updated MacKernelSDK" && git push || echo "Done"
# [...]
```

Idk if would it be better, but I want to propose it...
