### ISSUE TITLE
AppleALC and Lilu Actions failure

### ISSUE THREAD

**Issue by vandroiy2013** [acidanthera/bugtracker#2399]
Problems with  Build, Clang and Coverity
<img width="1297" alt="Знімок екрана 2024-05-06 о 14 15 45" src="https://github.com/acidanthera/bugtracker/assets/8144780/9f4df391-5282-4a36-8724-227c919e7829">

**Comment by vit9696** [comment]
```
clang-12: error: unknown argument: '-ivfsstatcache'
clang-12: error: cannot specify -o when generating multiple output files
```

This can be related.

**Comment by vit9696** [comment]
Primary reason is macOS 14 upgrade on GH side: https://github.com/actions/runner-images/issues/9255.
I tried to temporarily revert to macOS 12, but that will not work soon:
https://github.com/acidanthera/AppleALC/commit/60b289eea116c141d7cea50baee91931f5296ea6

**Comment by vandroiy2013** [comment]
For now this problem is partially solved but we need stable solution for macOS 14 runners in future.   
All kexts from 2024.05 release planning builds correctly and we ready to release.

**Comment by Lorys89** [comment]
Applealc after the merge pr is broken goes in kp

**Comment by Lorys89** [comment]
After this revert it starts working again and starts OS
https://github.com/Lorys89/AppleALC/actions/runs/8971143624

**Comment by vandroiy2013** [comment]
cc @vit9696

**Comment by vandroiy2013** [comment]
Fixed

**Comment by dreamwhite** [comment]
Just wondering... before merging these layout-ids which will certainly cause issues when using `real` XML key, shouldn't be it better to run an action to check the integrity of the XML like files (`Info.plist` in this specific case)?

Something like:

```yaml
name: Check XML Files for 'real' key

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-xml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install xmllint
        run: sudo apt-get install libxml2-utils

      - name: Find 'real' Key in XML Files
        run: |
          find . -name "*.xml" -type f -exec xmllint --xpath '//real' {} \; | grep -q real && echo "::error::Found 'real' key. Consider using 'int' instead." || echo "No 'real' key found."

```
